Name: meowcloud.action
ListenOn: 0.0.0.0:8080
Mode: test
Log:
  Encoding: json
  Level: debug
  Stat: false
Mongo:
  URL: mongodb+srv://root:FhfzRPcLfF@mongodb-headless.mongodb.svc.cluster.local/?tls=false
  DB: meowcloud_action_test
Cache:
  - Host: redis-master.redis:6379
Telemetry:
  Endpoint: http://jaeger-collector.istio-system:14268/api/traces